services:
  backend:
    image: booking-backend
    pull_policy: never
    container_name: booking-backend
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    secrets:
      - backend_config

  frontend:
    image: booking-frontend
    pull_policy: never
    container_name: booking-frontend
    build:
      context: ./frontend
      target: development
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
    ports:
      - 5173:5173
  
  database:
    image: postgres:17.7-bookworm
    container_name: booking-database
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/database_password
    secrets:
      - database_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

secrets:
  backend_config:
    file: backend/config.ini
  database_password:
    file: ./database_password.txt

volumes:
  postgres-data:
